AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pecuniary Account Query services

Parameters:
  AppName:
    Description: Application name
    Type: String
    Default: Pecuniary
  PecuniaryStackParameter:
    Type: String
    Default: pecuniary-stack

Mappings:
  Constants:
    Application: 
      Name: Pecuniary

Globals:
  Function:
    Timeout: 30

Resources:
  PecuniaryWebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: 
                Fn::Sub:
                    - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
                    - UserPoolId:
                        Fn::ImportValue:
                          !Sub ${PecuniaryStackParameter}-PecuniaryCognitoUserPoolId
            Identity:
              Header: Authorization
      Tags:
        AppName: !FindInMap [Constants, Application, Name]

  AccountEvent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-AccountEvent
      Handler: Pecuniary.Events.AccountEvent::Pecuniary.Events.AccountEvent.Function::AccountEventHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: src/Pecuniary.Events.AccountEvent/bin/Debug/netcoreapp2.1/publish
      MemorySize: 384
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          ElasticSearchDomain:
            Fn::ImportValue:
              !Sub ${PecuniaryStackParameter}-PecuniaryESReadStoreDomain
      Events:
        AccountCreatedEventTopic:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                !Sub ${PecuniaryStackParameter}-PecuniaryAccountCreatedEventTopicArn
        AccountUpdatedEventTopic:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                !Sub ${PecuniaryStackParameter}-PecuniaryAccountUpdatedEventTopicArn
      Policies: 
        - AmazonSNSReadOnlyAccess
      Tags:
        AppName: !Ref AppName 

  AccountQueryWebApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-AccountQuery
      Handler: Pecuniary.WebApi.AccountQuery::Pecuniary.WebApi.AccountQuery.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: src/Pecuniary.WebApi.AccountQuery/bin/Debug/netcoreapp2.1/publish
      MemorySize: 384
      Environment:
        Variables:
          ElasticSearchDomain:
            Fn::ImportValue:
              !Sub ${PecuniaryStackParameter}-PecuniaryESReadStoreDomain
      Events:
        GetValues:
          Type: Api
          Properties:
            RestApiId: !Ref PecuniaryWebApi
            Path: /api/account/{id}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
      Tags:
         AppName: !Ref AppName
