AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pecuniary Account query microservice

Parameters:
  AppName:
    Description: Application name
    Type: String
    Default: Pecuniary
  PecuniaryAuthStackParameter:
    Type: String
    Default: pecuniary-auth-stack
  PecuniaryDbStackParameter:
    Type: String
    Default: pecuniary-db-stack
  PecuniaryTopicsStackParameter:
    Type: String
    Default: pecuniary-topics-stack

Mappings:
  Constants:
    Application: 
      Name: Pecuniary

Globals:
  Function:
    Timeout: 30

Resources:
  PecuniaryWebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: 
                Fn::Sub:
                    - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
                    - UserPoolId:
                        Fn::ImportValue:
                          !Sub ${PecuniaryAuthStackParameter}-PecuniaryCognitoUserPoolId
            Identity:
              Header: Authorization
      Tags:
        AppName: !FindInMap [Constants, Application, Name]

  AccountEvent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-AccountEvent
      Handler: Pecuniary.Account.Events::Pecuniary.Account.Events.Function::AccountEventHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: Pecuniary.Account.Events/bin/Release/netcoreapp2.1/publish
      MemorySize: 384
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          ElasticSearchDomain:
            Fn::ImportValue:
              !Sub ${PecuniaryDbStackParameter}-PecuniaryESReadStoreDomain
      Events:
        AccountCreatedEventTopic:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                !Sub ${PecuniaryTopicsStackParameter}-PecuniaryAccountCreatedEventTopicArn
        AccountUpdatedEventTopic:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                !Sub ${PecuniaryTopicsStackParameter}-PecuniaryAccountUpdatedEventTopicArn
      Policies: 
        - AmazonSNSReadOnlyAccess
      Tags:
        AppName: !Ref AppName 

  AccountQueryWebApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pecuniary-AccountQuery
      Handler: Pecuniary.Account.Query::Pecuniary.Account.Query.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore2.1
      CodeUri: Pecuniary.Account.Query/bin/Release/netcoreapp2.1/publish
      MemorySize: 384
      Environment:
        Variables:
          ElasticSearchDomain:
            Fn::ImportValue:
              !Sub ${PecuniaryDbStackParameter}-PecuniaryESReadStoreDomain
      Events:
        GetValues:
          Type: Api
          Properties:
            RestApiId: !Ref PecuniaryWebApi
            Path: /api/account/{id}
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
      Tags:
         AppName: !Ref AppName

Outputs:
  PecuniaryApiGatewayBaseUrl:
    Description: Base Url of the Pecuniary Account Query API Gateway
    Value: !Ref PecuniaryWebApi
    Export:
      Name: !Sub ${AWS::StackName}-PecuniaryApiGatewayBaseUrl